server:
  port: 8005
spring:
  redis:
    database: 0
    host: 192.168.47.132
    port: 6379
    password: 123321
#在dev环境下开启mybatis的日志打印
mybatis:
  configuration:
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
#设置域名，在java代码中获取，这里是资源配置
website:
  domain-name: imoocnews.com
